### ISSUE TITLE
Wrong constant for empty stream

### ISSUE THREAD

**Issue by mcasimir** [nicdex/eventstore-node#1]
Hi,
i'd like to say a big thank you for this client, is the most complete we found for node.

I've found a small bug here: https://github.com/nicdex/eventstore-node/blob/master/lib/dist.js#L54, as per spec the empty stream should be 0 and not -1.

It would be really nice to see some documentation. If i've some time i'll try to help. Thanks!

**Comment by nicdex** [comment]
First of all sorry for the delay, I've didn't have time to update that project lately. Also somehow my github notifications are turned off otherwise I would have answered sooner than this.

This is a port of the .Net client, the code is closely as possible to the original. As you can see here https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.ClientAPI/ExpectedVersion.cs EmptyStream value is -1. That being said, function documentation seems to says it should be 0. Please open a ticket on the EventStore github project to get confirmation/change and I will gladly port the change if any.

Thank you.
